# board_id will be one of the following:
# - "main" for the main Robot MCU
# - "remote" for the Remote MCU
# - "safety" for the Safety Mechanism MCU
# See block diagram in Obsidian: obsidian://open?vault=Supervault&file=Robotics%2F3.%20Robo-Magellan%2FRobo-Magellan%20Bot
board_id = "main"

[wifi]
ssid = ""
password = ""
